development:
  solr:
    hostname: solr
    port: 8983
    log_level: INFO

test:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING

production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
  auto_commit_after_request: false
